name: Setup Workspace
author: Maiko Tan
description: 'Setup workspace for building our project'
inputs:
  node-version:
    type: string
    description: 'Node.js version'
    required: true
    default: '20'
  yarn-berry:
    type: boolean
    description: 'Force Use Yarn Berry'
    required: false
    default: false
  yarn-no-immutable:
    type: boolean
    description: 'Disable Yarn Immutable'
    required: false
    default: false
  yarn-pnp:
    type: boolean
    description: 'Use Yarn PnP'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Use Yarn Berry
      id: yarn-berry
      if: ${{ inputs.yarn-berry }}
      shell: bash
      run: |
        # Test if current yarn version is 1.x
        if [[ $(yarn --version) == 1.* ]]; then
          echo "Installing Yarn Berry..."
          yarn set version berry
        else
          echo "Yarn Berry is already installed"
        fi
        echo "ENSURE_YARN_BERRY=true" >> $GITHUB_ENV

    - name: Check Immutable Installs
      if: ${{ inputs.yarn-no-immutable }}
      shell: bash
      run: |
        if [[ $ENSURE_YARN_BERRY == true ]]; then
          yarn config set enableImmutableInstalls false
        fi
        echo "YARN_ENABLE_IMMUTABLE_INSTALLS=false" >> $GITHUB_ENV

    - name: Use Yarn PnP
      if: ${{ inputs.yarn-pnp && inputs.yarn-berry }}
      shell: bash
      run: |
        yarn config set nodeLinker ${{ inputs.yarn-pnp && 'pnp' || 'node-modules' }}

    - name: Install Dependencies
      shell: bash
      run: |
        yarn
