name: Build

on:
  workflow_call:
    inputs:
      lint:
        type: boolean
        description: 'Run lint'
        required: false
        default: false
      test:
        type: boolean
        description: 'Run test'
        required: false
        default: false
      approve:
        type: boolean
        description: 'Approve pull request if all jobs are successful'
        required: false
        default: false
      review-message:
        type: string
        description: 'Review message for auto approve'
        required: false
        default: ''
      node-version:
        type: string
        description: 'Node.js version'
        required: false
        default: '20'
      yarn-berry:
        type: boolean
        description: 'Force Use Yarn Berry'
        required: false
        default: false
      yarn-no-immutable:
        type: boolean
        description: 'Disable Yarn Immutable'
        required: false
        default: false
      yarn-pnp:
        type: boolean
        description: 'Use Yarn PnP'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Workspace
        uses: AwesomeHamster/workflows/.github/actions/setup-workspace@master
        with:
          node-version: ${{ inputs.node-version }}
          yarn-berry: ${{ inputs.yarn-berry }}
          yarn-no-immutable: ${{ inputs.yarn-no-immutable }}
          yarn-pnp: ${{ inputs.yarn-pnp }}

      - name: Build
        run: yarn build

      - name: Upload Artifact
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref }}
          path: './'
          retention-days: 1

  lint:
    runs-on: ubuntu-latest
    if: ${{ inputs.lint }}
    steps:
      - name: Setup Workspace
        uses: AwesomeHamster/workflows/.github/actions/setup-workspace@master
        with:
          node-version: ${{ inputs.node-version }}
          yarn-berry: ${{ inputs.yarn-berry }}
          yarn-no-immutable: ${{ inputs.yarn-no-immutable }}
          yarn-pnp: ${{ inputs.yarn-pnp }}

      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    if: ${{ inputs.test }}
    steps:
      - name: Setup Workspace
        uses: AwesomeHamster/workflows/.github/actions/setup-workspace@master
        with:
          node-version: ${{ inputs.node-version }}
          yarn-berry: ${{ inputs.yarn-berry }}
          yarn-no-immutable: ${{ inputs.yarn-no-immutable }}
          yarn-pnp: ${{ inputs.yarn-pnp }}

      - name: Test
        run: yarn test

  approve:
    runs-on: ubuntu-latest
    needs: [build, lint, test]
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize') && github.event.number && inputs.approve }}
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: ${{ inputs.review-message || '🎉 You have passed all checks, good job! 🎉' }}
          pull-request-number: ${{ github.event.number }}
